services:
    laravel-filament-web:
        container_name: laravel-filament-web
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./public:/var/www/html
            - .:/var/www
        networks:
            - laravel-filament
        ports:
            - 7271:80
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/up"]
            interval: 30s
            timeout: 10s
            retries: 5
#            env_file:
#                - .env

networks:
    laravel-filament:
        driver: bridge
